import { Company } from '@prisma/client'
export const mockCompanies: Company[] = [
  {
    id: '65f1a1a1a1a1a1a1a1a1a1a1',
    userId: '64u1',
    name: 'Acme Technologies',
    logo: null,
    description: 'Enterprise SaaS platform',
    industry: 'Software',
    companySize: '51-200',
    foundedYear: 2018,
    website: 'https://acme.com',
    linkedinProfile: null,
    location: 'Bangalore, India',
    contactEmail: 'hr@acme.com',
    contactPhone: null,
    address: null,
    businessDocument: null,
    taxDocument: null,
    status: 'PENDING',
    rejectionReason: null,
    approvedAt: null,
    approvedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '65f1b2b2b2b2b2b2b2b2b2b2',
    userId: '64u2',
    name: 'FinStack',
    logo: null,
    description: 'Fintech infrastructure',
    industry: 'FinTech',
    companySize: '11-50',
    foundedYear: 2020,
    website: 'https://finstack.io',
    linkedinProfile: null,
    location: 'Mumbai, India',
    contactEmail: 'careers@finstack.io',
    contactPhone: null,
    address: null,
    businessDocument: null,
    taxDocument: null,
    status: 'APPROVED',
    rejectionReason: null,
    approvedAt: new Date(),
    approvedBy: 'admin_1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '65f1c3c3c3c3c3c3c3c3c3c3',
    userId: '64u3',
    name: 'Healthify',
    logo: null,
    description: 'Healthcare platform',
    industry: 'Healthcare',
    companySize: '201-500',
    foundedYear: 2015,
    website: null,
    linkedinProfile: null,
    location: 'London, UK',
    contactEmail: 'jobs@healthify.com',
    contactPhone: null,
    address: null,
    businessDocument: null,
    taxDocument: null,
    status: 'REJECTED',
    rejectionReason: 'Invalid documents, Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore sunt error ab autem ratione facere, vero debitis deleniti ad odit amet esse ex omnis delectus, id nemo quam! Maxime natus accusamus ducimus expedita cumque nihil eum vero, dolore quae qui culpa nulla harum deleniti eius recusandae sed quasi unde perspiciatis, temporibus tempore officiis repudiandae laborum. Quisquam praesentium iure, exercitationem molestias modi consequuntur quasi? Rerum sequi fuga, suscipit impedit corporis, ullam itaque porro ex magnam, culpa esse corrupti ipsam nesciunt repellat eum. Nemo quis in consequuntur corporis praesentium vitae, doloribus laudantium voluptas eaque perspiciatis amet, sequi quo itaque, repudiandae cumque fugiat.',
    approvedAt: null,
    approvedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
] as const
