import React from "react"

export default function SignedUrlFailureEmail({ error, link }: { error: string, link: string }) {
  return (
    <div style={{ fontFamily: "Arial, sans-serif", lineHeight: "1.6", padding: "20px", color: "#111" }}>
      <h2 style={{ color: "#dc2626" }}>
        🚨 Signed URL Refresh Cron Failed
      </h2>
      <p>
        The scheduled cron job responsible for refreshing <strong>avatar and company logo signed URLs</strong> has failed.
      </p>
      <p>
        This job ensures that image URLs stored in the database remain valid before their expiration period.
        If the job does not run successfully, user avatars and company logos may stop loading after their signed URLs expire.
      </p>
      <hr style={{ margin: "20px 0" }} />
      <h3>⚠️ Error Details</h3>
      <pre
        style={{
          background: "#f3f4f6",
          padding: "12px",
          borderRadius: "6px",
          overflowX: "auto",
          fontSize: "13px"
        }}
      >
        {error}
      </pre>
      <p><strong>Failure Time:</strong> {new Date().toISOString()}</p>
      <hr style={{ margin: "20px 0" }} />
      <h3>🛠 Recommended Action</h3>
      <p>
        You can manually trigger the signed URL refresh endpoint using the link below.
      </p>
      <p>
        <a
          href={link}
          style={{
            display: "inline-block",
            padding: "10px 16px",
            background: "#2563eb",
            color: "#fff",
            textDecoration: "none",
            borderRadius: "6px",
            fontWeight: "bold"
          }}
        >
          Run Signed URL Refresh
        </a>
      </p>
      <p style={{ marginTop: "20px", fontSize: "13px", color: "#6b7280" }}>
        This email was automatically generated by the HireFlow cron monitoring system.
      </p>
    </div>
  )
}